package com.zlebank.zplatform.sms.pojo;
// default package
// Generated 2016-1-11 14:51:02 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TTxnsSms generated by hbm2java
 */
@Entity
@Table(name = "t_txns_sms")
public class PojoTxnsSms implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7332538637954882079L;
	private long tid;
	private String tn;
	private String mobile;
	private String verifycode;
	private String content;
	private String sendtime;
	private String overduetime;
	private String busicode;
	private String busitype;
	private String retcode;
	private String retinfo;
	private String moduletype;

	public PojoTxnsSms() {
	}

	public PojoTxnsSms(long tid, String tn, String mobile, String verifycode,
			String content, String sendtime, String overduetime) {
		this.tid = tid;
		this.tn = tn;
		this.mobile = mobile;
		this.verifycode = verifycode;
		this.content = content;
		this.sendtime = sendtime;
		this.overduetime = overduetime;
	}

	public PojoTxnsSms(long tid, String tn, String mobile, String verifycode,
			String content, String sendtime, String overduetime,
			String busicode, String busitype, String retcode, String retinfo,
			String moduletype) {
		this.tid = tid;
		this.tn = tn;
		this.mobile = mobile;
		this.verifycode = verifycode;
		this.content = content;
		this.sendtime = sendtime;
		this.overduetime = overduetime;
		this.busicode = busicode;
		this.busitype = busitype;
		this.retcode = retcode;
		this.retinfo = retinfo;
		this.moduletype = moduletype;
	}

	@Id
	@Column(name = "TID", unique = true, nullable = false, precision = 12, scale = 0)
	public long getTid() {
		return this.tid;
	}

	public void setTid(long tid) {
		this.tid = tid;
	}

	@Column(name = "TN", nullable = false, length = 18)
	public String getTn() {
		return this.tn;
	}

	public void setTn(String tn) {
		this.tn = tn;
	}

	@Column(name = "MOBILE", nullable = false, length = 11)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "VERIFYCODE", nullable = false, length = 6)
	public String getVerifycode() {
		return this.verifycode;
	}

	public void setVerifycode(String verifycode) {
		this.verifycode = verifycode;
	}

	@Column(name = "CONTENT", nullable = false, length = 256)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "SENDTIME", nullable = false, length = 14)
	public String getSendtime() {
		return this.sendtime;
	}

	public void setSendtime(String sendtime) {
		this.sendtime = sendtime;
	}

	@Column(name = "OVERDUETIME", nullable = false, length = 14)
	public String getOverduetime() {
		return this.overduetime;
	}

	public void setOverduetime(String overduetime) {
		this.overduetime = overduetime;
	}

	@Column(name = "BUSICODE", length = 8)
	public String getBusicode() {
		return this.busicode;
	}

	public void setBusicode(String busicode) {
		this.busicode = busicode;
	}

	@Column(name = "BUSITYPE", length = 4)
	public String getBusitype() {
		return this.busitype;
	}

	public void setBusitype(String busitype) {
		this.busitype = busitype;
	}

	@Column(name = "RETCODE", length = 3)
	public String getRetcode() {
		return this.retcode;
	}

	public void setRetcode(String retcode) {
		this.retcode = retcode;
	}

	@Column(name = "RETINFO", length = 256)
	public String getRetinfo() {
		return this.retinfo;
	}

	public void setRetinfo(String retinfo) {
		this.retinfo = retinfo;
	}

	@Column(name = "MODULETYPE", length = 4)
	public String getModuletype() {
		return this.moduletype;
	}

	public void setModuletype(String moduletype) {
		this.moduletype = moduletype;
	}

}
