package com.zlebank.zplatform.commons.dao.pojo;
// Generated 2015-11-4 13:14:53 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TUploadLog generated by hbm2java
 */
@Entity
@Table(name = "T_UPLOAD_LOG")
public class PojoUploadLog implements java.io.Serializable {

    /**
	 * 
	 */
	private static final long serialVersionUID = -5920627030533166615L;
	private long logid;
    private String filename;
    private Byte reuploadcount;
    private Long caId;
    private String uploadtime;
    private String caName;
    private long uploaderid;
    private String reuploadtime;
    private String uploadername;
    private String recode;
    private String notes;
    private String remarks;
    private String fileurl;

    public PojoUploadLog() {
    }

    public PojoUploadLog(long logid, String filename, long uploaderid,
            String uploadername) {
        this.logid = logid;
        this.filename = filename;
        this.uploaderid = uploaderid;
        this.uploadername = uploadername;
    }
    public PojoUploadLog(long logid, String filename, Byte reuploadcount,
            Long caId, String uploadtime, String caName, long uploaderid,
            String reuploadtime, String uploadername, String recode,
            String notes, String remarks, String fileurl) {
        this.logid = logid;
        this.filename = filename;
        this.reuploadcount = reuploadcount;
        this.caId = caId;
        this.uploadtime = uploadtime;
        this.caName = caName;
        this.uploaderid = uploaderid;
        this.reuploadtime = reuploadtime;
        this.uploadername = uploadername;
        this.recode = recode;
        this.notes = notes;
        this.remarks = remarks;
        this.fileurl = fileurl;
    }

    @Id
    @Column(name = "LOGID", unique = true, nullable = false, precision = 10, scale = 0)
    public long getLogid() {
        return this.logid;
    }

    public void setLogid(long logid) {
        this.logid = logid;
    }

    @Column(name = "FILENAME", nullable = false, length = 64)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name = "REUPLOADCOUNT", precision = 2, scale = 0)
    public Byte getReuploadcount() {
        return this.reuploadcount;
    }

    public void setReuploadcount(Byte reuploadcount) {
        this.reuploadcount = reuploadcount;
    }

    @Column(name = "CA_ID", precision = 10, scale = 0)
    public Long getCaId() {
        return this.caId;
    }

    public void setCaId(Long caId) {
        this.caId = caId;
    }

    @Column(name = "UPLOADTIME", length = 32)
    public String getUploadtime() {
        return this.uploadtime;
    }

    public void setUploadtime(String uploadtime) {
        this.uploadtime = uploadtime;
    }

    @Column(name = "CA_NAME", length = 32)
    public String getCaName() {
        return this.caName;
    }

    public void setCaName(String caName) {
        this.caName = caName;
    }

    @Column(name = "UPLOADERID", nullable = false, precision = 10, scale = 0)
    public long getUploaderid() {
        return this.uploaderid;
    }

    public void setUploaderid(long uploaderid) {
        this.uploaderid = uploaderid;
    }

    @Column(name = "REUPLOADTIME", length = 32)
    public String getReuploadtime() {
        return this.reuploadtime;
    }

    public void setReuploadtime(String reuploadtime) {
        this.reuploadtime = reuploadtime;
    }

    @Column(name = "UPLOADERNAME", nullable = false, length = 64)
    public String getUploadername() {
        return this.uploadername;
    }

    public void setUploadername(String uploadername) {
        this.uploadername = uploadername;
    }

    @Column(name = "RECODE", length = 2)
    public String getRecode() {
        return this.recode;
    }

    public void setRecode(String recode) {
        this.recode = recode;
    }

    @Column(name = "NOTES", length = 128)
    public String getNotes() {
        return this.notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    @Column(name = "REMARKS", length = 128)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "FILEURL", length = 128)
    public String getFileurl() {
        return this.fileurl;
    }

    public void setFileurl(String fileurl) {
        this.fileurl = fileurl;
    }

}
